kind: pipeline
name: default



steps:

  # Build docker image:
  - name: docker
    image: plugins/docker
    storage_driver: overlay
    when:
      branch: master
    settings:
      repo: docker.stackdot.com/polygon/go-ceph
      registry: docker.stackdot.com
      tag:
        - '${DRONE_BRANCH/master/latest}'
        - '${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
