---
kind: pipeline
name: build dry run

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    dry_run: true
    repo: polygonio/go-ceph
    tag:
    - ${DRONE_BRANCH/master/latest}
    - ${DRONE_COMMIT}

trigger:
  branch:
  - master
  event:
  - pull_request

---
kind: pipeline
name: build and push

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    password:
      from_secret: dockerhub_password
    repo: polygonio/go-ceph
    tag:
    - ${DRONE_BRANCH/master/latest}
    - ${DRONE_COMMIT}
    username:
      from_secret: dockerhub_username

trigger:
  branch:
  - master
  event:
  - push

...
